<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<div class="form-horizontal">
<div class="col-sm-6">
    <div class="form-group">
        <label for="MainContent_text_reg_nombre" class="col-sm-4 control-label">Empresa*:</label>
        <div class="col-sm-8">
            <input name="ctl00$MainContent$text_reg_nombre" id="MainContent_text_reg_nombre" class="form-control" type="text">
        </div>
    </div>
    <div class="form-group">
        <label for="MainContent_text_reg_telefono" class="col-sm-4 control-label">Teléfono:</label>
        <div class="col-sm-8">
            <input name="ctl00$MainContent$text_reg_telefono" id="MainContent_text_reg_telefono" class="form-control" type="text">
        </div>
    </div>
    <div class="form-group">
        <label for="MainContent_text_reg_email" class="col-sm-4 control-label">Email:</label>
        <div class="col-sm-8">
            <input name="ctl00$MainContent$text_reg_email" id="MainContent_text_reg_email" class="form-control" type="text">
        </div>
    </div>
    <div class="form-group">
        <label for="MainContent_text_reg_web" class="col-sm-4 control-label">Web:</label>
        <div class="col-sm-8">
            <input name="ctl00$MainContent$text_reg_web" id="MainContent_text_reg_web" class="form-control" type="text">
        </div>
    </div>
</div>
<div class="col-sm-6">
    <div class="form-group">
        <label for="MainContent_text_reg_direccion" class="col-sm-4 control-label">Dirección:</label>
        <div class="col-sm-8">
            <input name="ctl00$MainContent$text_reg_direccion" id="MainContent_text_reg_direccion" class="form-control" onkeyup="sync()" type="text">
        </div>
    </div>
    <div class="form-group">
        <label for="MainContent_text_reg_localidad" class="col-sm-4 control-label">Localidad:</label>
        <div class="col-sm-8">
            <input name="ctl00$MainContent$text_reg_localidad" id="MainContent_text_reg_localidad" class="form-control" onkeyup="sync()" type="text">
        </div>
    </div>
    <div class="form-group">
        <label for="MainContent_text_reg_provincia" class="col-sm-4 control-label">Provincia:</label>
        <div class="col-sm-8">
            <input name="ctl00$MainContent$text_reg_provincia" id="MainContent_text_reg_provincia" class="form-control" onkeyup="sync()" type="text">
        </div>
    </div>
    <div class="form-group">
        <label for="MainContent_text_reg_cp" class="col-sm-4 control-label">CP:</label>
        <div class="col-sm-8">
            <input name="ctl00$MainContent$text_reg_cp" id="MainContent_text_reg_cp" class="form-control" onkeyup="sync()" type="text">
    
</body>
</html>